In [124]:
import pandas as pd
scriptdata = pd.read_csv("C:/Users/Savita/Desktop/ml/prediction_gender/data/orig_data.csv")


In [125]:
scriptdata.head(2)

_id  \
0  5ddb4e1a90281a177983e57c   
1  5ddb4e2b90281a177983e598   

                                   allbrowsercookies    bot brand browser  \
0  ["__gads=ID=4ac600ce86bc98a5:T=1569838984:S=AL...  False   NaN  Chrome   
1  ["__gads=ID=4ac600ce86bc98a5:T=1569838984:S=AL...  False   NaN  Chrome   

   cookies.XSRF-TOKEN                             cookies.__cfduid  \
0                 NaN  d74390cf7ecf49d02be7084c106884ffd1574653464   
1                 NaN  d0ce46f9b728fd9e5ef5ec2b36a0bffac1574653481   

   cookies.cyber_astro_session      date  description  ...       os  \
0                          NaN  26-11-19  description  ...  Windows   
1                          NaN  26-11-19  description  ...  Windows   

                                  page_url    pc  \
0             https://www.facultyplus.com/  True   
1  https://www.facultyplus.com/engineering  True   

                                   referer tablet     time  \
0             https://www.facultyplus.com/  False  9:14:23   
1  https://www.facultyplus.com/engineering  False  9:14:39   

                                               title  touch  \
0  FacultyPlus - Indian Faculty Jobs - Assistant ...  False   
1                 engineering Archives - FacultyPlus  False   

              user_id visit_num  
0  MjY3_117.240.189.2      25.0  
1  MjY3_117.240.189.2      26.0  

[2 rows x 42 columns]

In [126]:
print(scriptdata.columns.values)

['_id' 'allbrowsercookies' 'bot' 'brand' 'browser' 'cookies.XSRF-TOKEN'
 'cookies.__cfduid' 'cookies.cyber_astro_session' 'date' 'description'
 'device' 'device_address' 'google_id' 'host_name' 'image_text'
 'impression' 'ip' 'keywords' 'language' 'local_hostname' 'location.IPv4'
 'location.city' 'location.country_code' 'location.country_name'
 'location.latitude' 'location.longitude' 'location.postal'
 'location.state' 'mobile' 'model' 'mylocalstorage' 'mysession' 'os'
 'page_url' 'pc' 'referer' 'tablet' 'time' 'title' 'touch' 'user_id'
 'visit_num']


In [127]:
scriptdata = scriptdata.drop(['_id','allbrowsercookies','bot','brand','browser','cookies.XSRF-TOKEN','cookies.__cfduid','cookies.cyber_astro_session','date','description','device','device_address','google_id','host_name',
 'image_text','impression','ip','language','local_hostname','location.IPv4','location.city','location.country_code','location.country_name','location.latitude','location.longitude','location.postal','location.state','mobile','model','mylocalstorage',
 'mysession','os','page_url','pc','referer','tablet','time','title','touch','user_id','visit_num'], axis = 1)

In [128]:
scriptdata = scriptdata.apply(lambda x: x.astype(str).str.lower())


In [129]:
scriptdata['name'] = scriptdata[scriptdata.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1)


In [130]:
scriptdata['name']=scriptdata.name.str.replace('\d+', '')

In [131]:
import string
scriptdata['name']= scriptdata['name'].str.replace('[!”#$%&’()*+,-./:;<=>?@[\]^_`{}~]'.format(string.punctuation), " ")

scriptdata.head(2)

keywords  \
0  facultyplus is an indian faculty jobs portal. ...   
1             engineering college teaching jobs 2018   

                                                name  
0  facultyplus is an indian faculty jobs portal  ...  
1                 engineering college teaching jobs

In [132]:
scriptdata= scriptdata['name'].str.split()

In [133]:
script= scriptdata.values.tolist()


In [134]:
from functools import reduce
flat_list = reduce(lambda x, y: x+y, script)


In [135]:
script = list(dict.fromkeys(flat_list))


In [136]:
str1 = ' '.join(script)


In [137]:
import pandas as pd
import spacy
nlp = spacy.load("en")
doc = nlp(str1) 
mylist = []
for token in doc: 
      mylist.append((token, token.pos_))


In [138]:
m_increment = 0
f_increment = 0
o_increment = 0
word_output1 = []
word_output2 =  []
word_output3 = []
for word in mylist:
    if word[-1] in ['INTJ','ADJ','ADV','DET','PRON']:
        word_output2.append(word)
        f_increment = f_increment + 1
  
    elif word[-1] in ['VERBS','NOUN','PROPN','ADP','AUXILARY','CCONJ','SCONJ','PART','prep']:
        word_output1.append(word)
        m_increment = m_increment + 1
        
    elif word[-1] in ['SYM','PUNCT','NUM','X']:
        word_output3.append(word)
        o_increment = o_increment + 1
        
        


In [139]:
from operator import itemgetter
res1 = list(map(itemgetter(0), word_output1)) 
res2 = list(map(itemgetter(0), word_output2)) 


In [140]:
m1_key = [str(x) for x in res1]
f1_key = [str(y) for y in res2]


In [141]:
unwanted_num = {'a', 'b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','x','y','z','vel', 'aaa', 'rd', 'nd', 'th', 'kg', 'pg', 'sr', 'st', 'csi', 'avs', 'scad', 'psn', 'npr', 'srm', 'trp', 'dpc', 'san', 'ksg', 'psg', 'rev', 'gr', 'vnr', 'rtmbs', 'kle', 'avn', 'gvg', 'dgim', 'byst', 'skd', 'ysr', 'gsfc', 'pmr', 'psv', 'rimt', 'gmr', 'sdnb', 'jct', 'kvsr', 'drbccc', 'pvkk', 'idrbt', 'srv', 'kpr', 'djr', 'bhu', 'bpr', 'ajk', 'psf', 'kgt', 'bt', 'gls', 'avp', 'aps', 'sns','ck','hkbk', 'qis', 'mvsr','mcm','nan', 'rbvrr', 'ggn', 'fdp', 'ndrk', 'svkm', 'nmims', 'kles', 'dyp', 'gd'} 
remove_gram1 = [ele for ele in m1_key if ele not in unwanted_num] 


In [142]:
unwanted_num = {'a', 'b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','x','y','z','vel', 'aaa', 'rd', 'nd', 'th', 'kg', 'pg', 'sr', 'st', 'csi', 'avs', 'scad', 'psn', 'npr', 'srm', 'trp', 'dpc', 'san', 'ksg', 'psg', 'rev', 'gr', 'vnr', 'rtmbs', 'kle', 'avn', 'gvg', 'dgim', 'byst', 'skd', 'ysr', 'gsfc', 'pmr', 'psv', 'rimt', 'gmr', 'sdnb', 'jct', 'kvsr', 'drbccc', 'pvkk', 'idrbt', 'srv', 'kpr', 'djr', 'bhu', 'bpr', 'ajk', 'psf', 'kgt', 'bt', 'gls', 'avp', 'aps', 'sns','ck', 'qis', 'mcm', 'rbvrr','nan', 'ggn', 'fdp', 'ndrk', 'svkm', 'nmims', 'kles', 'dyp', 'gd'} 
remove_gram2 = [ele for ele in f1_key if ele not in unwanted_num] 


In [143]:
v1 = 0
c1 = 0
v2 = 0
c2 = 0
c_f1 = []
v_f1 =  []
c_m2 = []
v_m2 =  []

for word in remove_gram2:
    if word[-1] in ['a','e','i','o','u']:
        v_f1.append(word)
        v1 = v1 + 1
  
    else:
        c_f1.append(word)
        c1 = c1 + 1
        
for word in remove_gram1:
    if word[-1] in ['a','e','i','o','u']:
        v_m2.append(word)
        v2 = v2 + 1
  
    else:
        c_m2.append(word)
        c2 = c2 + 1
        


In [145]:
word_cat1  =   c_m2 + c_f1
word_cat2   =   v_m2 + v_f1


In [146]:
import pandas as pd
data_type1 = pd.DataFrame(word_cat2)
data_type2 = pd.DataFrame(word_cat1)


In [147]:
data_type1.rename(columns = {0:'name'}, inplace = True) 
data_type2.rename(columns = {0:'name'}, inplace = True) 


In [148]:
data_type1.to_csv("C:/Users/Savita/Desktop/ml/prediction_gender/data/key1f.csv")
data_type2.to_csv("C:/Users/Savita/Desktop/ml/prediction_gender/data/key1m.csv")


In [149]:
data_type1['Gender'] = 'F'
data_type2['Gender'] = 'M'


In [150]:
original = data_type2.append(data_type1) 


In [151]:
original.to_csv("C:/Users/Savita/Desktop/ml/prediction_gender/data/data_preprocess.csv")


In [152]:
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score
np.random.seed(500)


In [153]:
original = pd.read_csv("C:/Users/Savita/Desktop/ml/prediction_gender/data/data_preprocess.csv")
original.head(2)


Unnamed: 0         name Gender
0           0  facultyplus      M
1           1      faculty      M

In [154]:
original['name'] = original['name'].str.capitalize() 


In [157]:
#original.to_csv("C:/Users/Savita/Desktop/ml/prediction_gender/data/mf_c.csv")

In [158]:
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(original['name'],original['Gender'],test_size=0.3)


In [159]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)


In [160]:
v = TfidfVectorizer(decode_error='replace', encoding='utf-8')
x = v.fit_transform(original['name'].values.astype('str'))  ## Even astype(str) would work


In [161]:
Tfidf_vect = TfidfVectorizer(max_features=2836)
Tfidf_vect.fit(original['name'])
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)


In [162]:
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)
predictions_NB = Naive.predict(Test_X_Tfidf)
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions_NB, Test_Y)*100)

Naive Bayes Accuracy Score ->  66.11842105263158


In [163]:
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(Train_X_Tfidf,Train_Y)
predictions_SVM = SVM.predict(Test_X_Tfidf)
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, Test_Y)*100)

SVM Accuracy Score ->  66.11842105263158


In [164]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(Train_X_Tfidf,Train_Y) 


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [165]:
y_pred = classifier.predict(Test_X_Tfidf)


In [7]:
def gender_features(word):
     return {'last_letter': word[-1]}


In [8]:
from nltk.corpus import names
labeled_names = ([(name, 'Male') for name in names.words('C:/Users/Savita/Desktop/PYTHON/ml/key1m.csv')] +
     [(name, 'Female') for name in names.words('C:/Users/Savita/Desktop/PYTHON/ml/key1f.csv')])
import random
random.shuffle(labeled_names)


In [9]:
import nltk
featuresets = [(gender_features(n), gender) for (n, gender) in labeled_names]
train_set, test_set = featuresets[700:], featuresets[:300]
classifier = nltk.NaiveBayesClassifier.train(train_set)


In [12]:
classifier.classify(gender_features('RAHUL'))


'Male'

In [170]:
print(nltk.classify.accuracy(classifier, test_set))


1.0


In [171]:
classifier.show_most_informative_features(10)

Most Informative Features


In [172]:
from nltk.classify import apply_features
train_set = apply_features(gender_features, labeled_names[700:])
test_set = apply_features(gender_features, labeled_names[:309])


In [173]:
def gender_features2(name):
    features = {}
    features["first_letter"] = name[0].lower()
    features["last_letter"] = name[-1].lower()
    for letter in 'abcdefghijklmnopqrstuvwxyz':
        features["count({})".format(letter)] = name.lower().count(letter)
        features["has({})".format(letter)] = (letter in name.lower())
    return features
 

In [174]:
featuresets = [(gender_features2(n), gender) for (n, gender) in labeled_names]
train_set, test_set = featuresets[700:], featuresets[:309]
classifier = nltk.NaiveBayesClassifier.train(train_set)
print(nltk.classify.accuracy(classifier, test_set))


0.9805825242718447


In [175]:
train_names = labeled_names[700:]
devtest_names = labeled_names[309:700]
test_names = labeled_names[:309]


In [176]:
train_set = [(gender_features(n), gender) for (n, gender) in train_names]
devtest_set = [(gender_features(n), gender) for (n, gender) in devtest_names]
test_set = [(gender_features(n), gender) for (n, gender) in test_names]
classifier = nltk.NaiveBayesClassifier.train(train_set) 
print(nltk.classify.accuracy(classifier, devtest_set))


0.9974424552429667


In [177]:
errors = []
for (name, tag) in devtest_names:
    guess = classifier.classify(gender_features(name))
if guess != tag:
    errors.append( (tag, guess, name) )


In [178]:
for (tag, guess, name) in sorted(errors):
    print('correct={:<8} guess={:<8s} name={:<30}'.format(tag, guess, name))

In [179]:
def gender_features(word):
    return {'suffix1': word[-1:],
            'suffix2': word[-2:]}

In [180]:
train_set = [(gender_features(n), gender) for (n, gender) in train_names]
devtest_set = [(gender_features(n), gender) for (n, gender) in devtest_names]
classifier = nltk.NaiveBayesClassifier.train(train_set)
print(nltk.classify.accuracy(classifier, devtest_set))


0.9974424552429667


In [181]:
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score
np.random.seed(500)


In [182]:
original = pd.read_csv("C:/Users/Savita/Desktop/ml/prediction_gender/data/data_preprocess.csv")
original.head(2)


Unnamed: 0         name Gender
0           0  facultyplus      M
1           1      faculty      M

In [183]:
original.size

3033

In [184]:
original.columns

Index(['Unnamed: 0', 'name', 'Gender'], dtype='object')

In [185]:
original.dtypes

Unnamed: 0     int64
name          object
Gender        object
dtype: object

In [186]:
original.isnull().isnull().sum()

Unnamed: 0    0
name          0
Gender        0
dtype: int64

In [187]:
original[original.Gender == 'F'].size

1122

In [188]:
original[original.Gender == 'M'].size

1911

In [189]:
df_names = original

In [190]:
df_names.Gender.replace({'F':0,'M':1},inplace=True)

In [191]:
df_names.Gender.unique()

array([1, 0], dtype=int64)

In [192]:
df_names.dtypes

Unnamed: 0     int64
name          object
Gender         int64
dtype: object

In [193]:
Xfeatures =df_names['name']

In [194]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(Xfeatures)

In [195]:
from sklearn.externals import joblib

In [196]:
gender_vectorizer = open("gender_vectorizer.pkl","wb")
joblib.dump(cv,gender_vectorizer)

In [197]:
gender_vectorizer.close()

In [198]:
cv.get_feature_names()

['abdul',
 'about',
 'abs',
 'academic',
 'academy',
 'accountant',
 'across',
 'adamas',
 'adani',
 'address',
 'adi',
 'adikavi',
 'aditya',
 'admin',
 'admission',
 'advertisement',
 'aeronautical',
 'agartala',
 'agra',
 'agricultural',
 'agriculture',
 'ahmed',
 'ahmedabad',
 'ajkim',
 'ajmer',
 'akal',
 'alagar',
 'alagesan',
 'aligarh',
 'allahabad',
 'aloysius',
 'alwin',
 'am',
 'ambal',
 'ambassador',
 'ambedkar',
 'ambiga',
 'amity',
 'ammal',
 'amman',
 'amravati',
 'amrita',
 'amritsar',
 'an',
 'anand',
 'ananthapuramu',
 'anchor',
 'and',
 'andal',
 'andhra',
 'angappa',
 'animal',
 'anna',
 'annamacharya',
 'annamalai',
 'announcement',
 'anurag',
 'anusandhan',
 'apeejay',
 'apollo',
 'application',
 'applications',
 'aravindar',
 'architecture',
 'arjun',
 'art',
 'article',
 'arts',
 'arulmurugan',
 'aruppukottai',
 'aryan',
 'as',
 'asansol',
 'assam',
 'assistant',
 'associate',
 'associated',
 'association',
 'at',
 'atria',
 'august',
 'aurangabad',
 'aurora',
 '

In [199]:
from sklearn.model_selection import train_test_split

In [200]:
X
y = df_names.name

In [210]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=42)

In [211]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)


0.0

In [212]:
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")
print("Accuracy of Model",clf.score(X_train,y_train)*100,"%")

Accuracy of Model 0.0 %
Accuracy of Model 100.0 %


In [213]:
sample_name = ["savita"]
vect = cv.transform(sample_name).toarray()
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [214]:
clf.predict(vect)

array(['abdul'], dtype='<U18')

In [215]:
def genderpredictor(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    if clf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")


In [216]:
def features(name):
    name = name.lower()
    return {
        'first-letter': name[0], # First letter
        'first2-letters': name[0:2], # First 2 letters
        'first3-letters': name[0:3], # First 3 letters
        'last-letter': name[-1],
        'last2-letters': name[-2:],
        'last3-letters': name[-3:],
    }

In [217]:
features = np.vectorize(features)
print(features(["Anna", "Henna", "Paras","rahul","shivani","Mohammed"]))

[{'first-letter': 'a', 'first2-letters': 'an', 'first3-letters': 'ann', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'h', 'first2-letters': 'he', 'first3-letters': 'hen', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'p', 'first2-letters': 'pa', 'first3-letters': 'par', 'last-letter': 's', 'last2-letters': 'as', 'last3-letters': 'ras'}
 {'first-letter': 'r', 'first2-letters': 'ra', 'first3-letters': 'rah', 'last-letter': 'l', 'last2-letters': 'ul', 'last3-letters': 'hul'}
 {'first-letter': 's', 'first2-letters': 'sh', 'first3-letters': 'shi', 'last-letter': 'i', 'last2-letters': 'ni', 'last3-letters': 'ani'}
 {'first-letter': 'm', 'first2-letters': 'mo', 'first3-letters': 'moh', 'last-letter': 'd', 'last2-letters': 'ed', 'last3-letters': 'med'}]


In [218]:
df_X = features(df_names['name'])

In [219]:
df_y = df_names['Gender']

In [220]:
from sklearn.feature_extraction import DictVectorizer
corpus = features(["Mike", "Julia"])
dv = DictVectorizer()
dv.fit(corpus)
transformed = dv.transform(corpus)
print(transformed)
 

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (0, 10)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 8)	1.0
  (1, 11)	1.0


In [221]:
dv.get_feature_names()

['first-letter=j',
 'first-letter=m',
 'first2-letters=ju',
 'first2-letters=mi',
 'first3-letters=jul',
 'first3-letters=mik',
 'last-letter=a',
 'last-letter=e',
 'last2-letters=ia',
 'last2-letters=ke',
 'last3-letters=ike',
 'last3-letters=lia']

In [222]:
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(df_X, df_y, test_size=0.33, random_state=42)

In [223]:
dfX_train

array([{'first-letter': 'c', 'first2-letters': 'co', 'first3-letters': 'com', 'last-letter': 'e', 'last2-letters': 'ce', 'last3-letters': 'rce'},
       {'first-letter': 'a', 'first2-letters': 'ad', 'first3-letters': 'adm', 'last-letter': 'n', 'last2-letters': 'in', 'last3-letters': 'min'},
       {'first-letter': 'i', 'first2-letters': 'im', 'first3-letters': 'imm', 'last-letter': 'y', 'last2-letters': 'ly', 'last3-letters': 'ely'},
       {'first-letter': 's', 'first2-letters': 'sc', 'first3-letters': 'sc', 'last-letter': 'c', 'last2-letters': 'sc', 'last3-letters': 'sc'},
       {'first-letter': 'f', 'first2-letters': 'fa', 'first3-letters': 'fac', 'last-letter': 's', 'last2-letters': 'us', 'last3-letters': 'lus'},
       {'first-letter': 's', 'first2-letters': 'si', 'first3-letters': 'sin', 'last-letter': 'h', 'last2-letters': 'gh', 'last3-letters': 'ngh'},
       {'first-letter': 'r', 'first2-letters': 'ra', 'first3-letters': 'ram', 'last-letter': 'a', 'last2-letters': 'na', 'last

In [224]:
dv = DictVectorizer()
dv.fit_transform(dfX_train)


<677x1205 sparse matrix of type '<class 'numpy.float64'>'
	with 4062 stored elements in Compressed Sparse Row format>

In [225]:
from sklearn.tree import DecisionTreeClassifier
dclf = DecisionTreeClassifier()
my_xfeatures =dv.transform(dfX_train)
dclf.fit(my_xfeatures, dfy_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [226]:
sample_name_eg = ["Alka"]
transform_dv =dv.transform(features(sample_name_eg))


In [227]:
vect3 = transform_dv.toarray()
dclf.predict(vect3)

array([0], dtype=int64)

In [228]:
if dclf.predict(vect3) == 0:
    print("Female")
else:
    print("Male")

Female


In [229]:
print(dclf.score(dv.transform(dfX_train), dfy_train)) 
print(dclf.score(dv.transform(dfX_test), dfy_test))

1.0
1.0


In [230]:
from sklearn.externals import joblib

In [231]:
decisiontreModel = open("decisiontreemodel.pkl","wb")

In [232]:
joblib.dump(dclf,decisiontreModel)

In [233]:
decisiontreModel.close()

In [234]:
import pickle
dctreeModel = open("namesdetectormodel.pkl","wb")

In [235]:
pickle.dump(dclf,dctreeModel)

In [236]:
dctreeModel.close()

In [237]:
NaiveBayesModel = open("naivebayesgendermodel.pkl","wb")

In [238]:
joblib.dump(clf,NaiveBayesModel)

In [239]:
NaiveBayesModel.close()

In [240]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer


In [241]:
df = pd.read_csv('names_dataset.csv')

In [242]:
df.head()

index       name sex
0      0       Mary   F
1      1       Anna   F
2      2       Emma   F
3      3  Elizabeth   F
4      4     Minnie   F

In [243]:
df.size

285075

In [244]:
df.columns

Index(['index', 'name', 'sex'], dtype='object')

In [245]:
df.dtypes

index     int64
name     object
sex      object
dtype: object

In [246]:
df.isnull().isnull().sum()

index    0
name     0
sex      0
dtype: int64

In [247]:
df[df.sex == 'F'].size

181800

In [248]:
df[df.sex == 'M'].size

103275

In [249]:
df_name = df

In [250]:
df_name.sex.replace({'F':0,'M':1},inplace=True)

In [251]:
df_name.sex.unique()

array([0, 1], dtype=int64)

In [252]:
df_name.dtypes

index     int64
name     object
sex       int64
dtype: object

In [253]:
Xfeature =df_name['name']

In [254]:
cv = CountVectorizer()
X = cv.fit_transform(Xfeature)

In [255]:
from sklearn.externals import joblib

In [256]:
gender_vector = open("gender_vector.pkl","wb")
joblib.dump(cv,gender_vector)

In [257]:
gender_vector.close()

In [258]:
cv.get_feature_names()

['aaban',
 'aabha',
 'aabid',
 'aabriella',
 'aada',
 'aadam',
 'aadan',
 'aadarsh',
 'aaden',
 'aadesh',
 'aadhav',
 'aadhavan',
 'aadhi',
 'aadhira',
 'aadhvik',
 'aadhya',
 'aadhyan',
 'aadi',
 'aadian',
 'aadil',
 'aadin',
 'aadish',
 'aadison',
 'aadit',
 'aadith',
 'aadithya',
 'aaditri',
 'aaditya',
 'aadiv',
 'aadon',
 'aadrian',
 'aadrika',
 'aadrit',
 'aadvik',
 'aadvika',
 'aadya',
 'aadyn',
 'aafia',
 'aafreen',
 'aagam',
 'aage',
 'aagot',
 'aahaan',
 'aahan',
 'aahana',
 'aahil',
 'aahir',
 'aahliyah',
 'aahna',
 'aahron',
 'aaidan',
 'aaiden',
 'aaidyn',
 'aaila',
 'aailiyah',
 'aailyah',
 'aaima',
 'aaira',
 'aairah',
 'aaisha',
 'aaishah',
 'aaiyana',
 'aaiza',
 'aaja',
 'aajah',
 'aajaylah',
 'aajon',
 'aakanksha',
 'aakarsh',
 'aakash',
 'aakeem',
 'aakilah',
 'aakira',
 'aakiyah',
 'aakriti',
 'aala',
 'aalaiya',
 'aalaiyah',
 'aalana',
 'aalanah',
 'aalani',
 'aalap',
 'aalaya',
 'aalayah',
 'aalayiah',
 'aalayjah',
 'aalayna',
 'aalaysha',
 'aalaysia',
 'aalea',
 

In [259]:
from sklearn.model_selection import train_test_split

In [260]:
X
y = df_name.sex

In [261]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [262]:
from sklearn.naive_bayes import MultinomialNB
cl = MultinomialNB()
cl.fit(X_train,y_train)
cl.score(X_test,y_test)


0.6398163206734908

In [263]:
print("Accuracy of Model",cl.score(X_test,y_test)*100,"%")
print("Accuracy of Model",cl.score(X_train,y_train)*100,"%")

Accuracy of Model 63.98163206734908 %
Accuracy of Model 100.0 %


In [264]:
sample_name = ["savita"]
vect = cv.transform(sample_name).toarray()
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [265]:
cl.predict(vect)

array([0], dtype=int64)

In [266]:
sample_name1 = ["Mohit"]
vect1 = cv.transform(sample_name1).toarray()

In [267]:
cl.predict(vect1)

array([1], dtype=int64)

In [268]:
sample_name2 = ["Natasha"]
vect2 = cv.transform(sample_name2).toarray()

In [269]:
cl.predict(vect2)

array([0], dtype=int64)

In [270]:
sample_name3 = ["susha","riya","Ankur","mohit","savita","shivani","arun","jatin","karan","rahul"]
vect3 = cv.transform(sample_name3).toarray()

In [271]:
cl.predict(vect3)

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 1], dtype=int64)

In [272]:
def genderpredictor(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    if cl.predict(vector) == 0:
        print("Female")
    else:
        print("Male")
    

In [273]:
genderpredictor("Maria")

Female


In [274]:
namelist = ["mahi","sonu","Femina","Masha"]
for i in namelist:
    print(genderpredictor(i))

Female
None
Female
None
Female
None
Female
None


In [275]:
def feature(name):
    name = name.lower()
    return {
        'first-letter': name[0], # First letter
        'first2-letters': name[0:2], # First 2 letters
        'first3-letters': name[0:3], # First 3 letters
        'last-letter': name[-1],
        'last2-letters': name[-2:],
        'last3-letters': name[-3:],
    }

In [276]:
feature = np.vectorize(feature)
print(feature(["Anna", "Henna", "Paras","rahul","shivani","Mohammed"]))

[{'first-letter': 'a', 'first2-letters': 'an', 'first3-letters': 'ann', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'h', 'first2-letters': 'he', 'first3-letters': 'hen', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'p', 'first2-letters': 'pa', 'first3-letters': 'par', 'last-letter': 's', 'last2-letters': 'as', 'last3-letters': 'ras'}
 {'first-letter': 'r', 'first2-letters': 'ra', 'first3-letters': 'rah', 'last-letter': 'l', 'last2-letters': 'ul', 'last3-letters': 'hul'}
 {'first-letter': 's', 'first2-letters': 'sh', 'first3-letters': 'shi', 'last-letter': 'i', 'last2-letters': 'ni', 'last3-letters': 'ani'}
 {'first-letter': 'm', 'first2-letters': 'mo', 'first3-letters': 'moh', 'last-letter': 'd', 'last2-letters': 'ed', 'last3-letters': 'med'}]


In [277]:
df_X = feature(df_name['name'])

In [278]:
df_y = df_name['sex']

In [279]:
from sklearn.feature_extraction import DictVectorizer
 
corpus = feature(["Mike", "Julia"])
dv = DictVectorizer()
dv.fit(corpus)
transformed = dv.transform(corpus)
print(transformed)
 

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (0, 10)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 8)	1.0
  (1, 11)	1.0


In [280]:
dv.get_feature_names()

['first-letter=j',
 'first-letter=m',
 'first2-letters=ju',
 'first2-letters=mi',
 'first3-letters=jul',
 'first3-letters=mik',
 'last-letter=a',
 'last-letter=e',
 'last2-letters=ia',
 'last2-letters=ke',
 'last3-letters=ike',
 'last3-letters=lia']

In [281]:
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(df_X, df_y, test_size=0.33, random_state=42)

In [282]:
dfX_train

array([{'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'ele', 'last-letter': 'a', 'last2-letters': 'ia', 'last3-letters': 'nia'},
       {'first-letter': 'a', 'first2-letters': 'ad', 'first3-letters': 'adi', 'last-letter': 'l', 'last2-letters': 'il', 'last3-letters': 'dil'},
       {'first-letter': 'k', 'first2-letters': 'ka', 'first3-letters': 'kad', 'last-letter': 'e', 'last2-letters': 'ze', 'last3-letters': 'nze'},
       ...,
       {'first-letter': 'j', 'first2-letters': 'ja', 'first3-letters': 'jaz', 'last-letter': 'y', 'last2-letters': 'ly', 'last3-letters': 'zly'},
       {'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'elv', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'ina'},
       {'first-letter': 'l', 'first2-letters': 'le', 'first3-letters': 'led', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ger'}],
      dtype=object)

In [283]:
dv = DictVectorizer()
dv.fit_transform(dfX_train)


<63666x8194 sparse matrix of type '<class 'numpy.float64'>'
	with 381996 stored elements in Compressed Sparse Row format>

In [284]:
from sklearn.tree import DecisionTreeClassifier
dcl = DecisionTreeClassifier()
my_xfeatures =dv.transform(dfX_train)
dcl.fit(my_xfeatures, dfy_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [285]:
sample_name_eg = ["Alka"]
transform_dv =dv.transform(features(sample_name_eg))


In [286]:
vect3 = transform_dv.toarray()

In [288]:
dcl.predict(vect3)

array([0], dtype=int64)

In [289]:
if dcl.predict(vect3) == 0:
    print("Female")
else:
    print("Male")

Female


In [290]:
name_eg1 = ["Charu"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dcl.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Female


In [291]:
def genderpredictor1(a):
    test_name1 = [a]
    transform_dv =dv.transform(features(test_name1))
    vector = transform_dv.toarray()
    if dcl.predict(vector) == 0:
        print("Female")
    else:
        print("Male")
    

In [292]:
random_name_list = ["Alok","Aman","rahul","Varsha","chandni","kalki"]

In [293]:
for n in random_name_list:
    print(genderpredictor1(n))

Male
None
Male
None
Male
None
Female
None
Female
None
Male
None


In [294]:
print(dcl.score(dv.transform(dfX_train), dfy_train)) 
print(dcl.score(dv.transform(dfX_test), dfy_test))

0.9888951716771903
0.8671513760005102


In [295]:
from sklearn.externals import joblib

In [296]:
decisiontreeModel = open("decisiontreemodelnew.pkl","wb")

In [297]:
joblib.dump(dcl,decisiontreeModel)

In [298]:
decisiontreeModel.close()

In [299]:
import pickle
randomforestModel = open("randomforestmodel.pkl","wb")

In [300]:
pickle.dump(dcl,randomforestModel)

In [301]:
randomforestModel.close()

In [302]:
NaiveBayesModel1 = open("naivebayesmodel.pkl","wb")

In [303]:
joblib.dump(cl,NaiveBayesModel1)

In [304]:
NaiveBayesModel.close()